version: '3.8'

services:
  app:
    image: docker-django-v0.0
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    container_name: django_container
    command: "python3 manage.py runserver 0.0.0.0:8000"
